### ISSUE TITLE
Allow test generator to determine what counts as failing

### ISSUE THREAD

**Issue by nickiaconis** [ember-cli/broccoli-lint-eslint#10]
What are your thoughts on allowing the test generator to determine what counts as failing?

Currently, the test generator is passed a list of error/warning messages, but has no way of differentiating between errors and warnings. This forces warnings to be treated as fail-worthy. If instead the result object was passed to the test generator, the test generator would be responsible, and thus free to, decide whether warnings are fail-worthy or not.

Here's a diff of more or less what's needed to make this work: https://github.com/nickiaconis/broccoli-eslinter/commit/4b15c569c1c45b60c45a65b1bf0567c95b4cfd40

Would you be interested in something like this?

**Comment by jonathanKingston** [comment]
Sorry I have read this a few times and it seems to me this could be managed in config just the same, granted there isn't a differentiation between the two.

I'm indifferent if others come along and want it then it can be added :smile:.

**Comment by nickiaconis** [comment]
Can you explain what you mean when you say "this could be managed in config just the same"?

What I see with the current test generator API is: for a file with 1 warning and 0 errors, the test generator will be passed an array of 1 messages, so it generates a failing test because it has no way of knowing that message was the result of a warning rather than an error.

**Comment by nickiaconis** [comment]
Ping @jonathanKingston.

> this could be managed in config just the same

Can you elaborate on how?

**Comment by BrianSipple** [comment]
I just encountered a situation where I think this would be highly useful as well. 

If I understand what you're alluding to @jonathanKingston, you could definitely overwrite the eslint configuration in tests to ignore certain rules, but I think what @nickiaconis is alluding to is the ability to have the linter warn -- and to see those warnings -- but still have tests pass. 

This would benefit anyone who wanted to use warnings as helpful reminders or FYIs, of sorts, but didn't want them to break the build, which is the current result when they occur in tests.

**Comment by nickiaconis** [comment]
@BrianSipple Bingo!

I was chatting with @rwjblue about how the jshint equivalent of this project handles warnings. He said the warning messages don't even get passed to the test generator, but that it might be useful, assuming we could tell them apart. Could be good to sync up on this idea. Maybe we could share a common test generator API?

**Comment by jonathanKingston** [comment]
Making the warnings not send to the test generator sounds a neater idea, that was my understanding of what was going off anyway. Letting a test generator decide on what to do with a warning sounds like it would lead to a long term headache of tests like "after x warnings make a fail" which sounds nice but in practice would likely lead to a maintenance nightmare.

I think if the warnings are not going to stdout or stderror at the moment that is a bug.

Personally I make everything fail as everything else is noise that just slows builds down and becomes similar to 'ad blindness'.

**Comment by jwlawrence** [comment]
I would like to see warnings be made pass-able as well. My use case is when I'm running a linter in Atom I want to see the warnings so I can decide what to do with them as I code, but when I run my tests I don't want them to fail due to warnings.

**Comment by nickiaconis** [comment]
@jonathanKingston Good point about "fail after x warnings" being a maintenance nightmare, although how developers write their test generators is not within our control. Here is a theoretical use case that may paint a better picture:

- Already have tooling to report on passed/skipped/failed tests
- No tooling to report on JS linting
- Adds broccoli-lint-eslint (or a consuming add-on) to the project
- Sets up errors and warnings for ESLint
- Wants to report on linting errors and warnings without writing more tooling
- Thinks to modify test reporting tools to accomplish this goal
- Writes a test generator that creates failing tests for errors and skipped tests for warnings
- Inside test reporter, filters ESLint tests and sums number failed and number skipped
- Prints these two numbers or sends them to an API

For a more specific use case (mine), I want to turn off failing tests for warnings altogether, so that I may use warnings as a style guide migration waypoint. A rule is activated as a warning while there are still examples of it in the codebase. The rule is reconfigured as an error when all examples have been removed. This eases the adoption of the rule, while minimizing the addition of new examples in the meantime.

**Comment by rwjblue** [comment]
> For a more specific use case (mine), I want to turn off failing tests for warnings altogether, so that I may use warnings as a style guide migration waypoint. A rule is activated as a warning while there are still examples of it in the codebase. The rule is reconfigured as an error when all examples have been removed. This eases the adoption of the rule, while minimizing the addition of new examples in the meantime.

This is exactly the scenario that I am in.  https://github.com/ember-cli/broccoli-lint-eslint/pull/38 passes the results through to `testGenerator` to do what it wishes.
