### ISSUE TITLE
Ability to fail Ember Build on ESLint Error?

### ISSUE THREAD

**Issue by Alonski** [ember-cli/broccoli-lint-eslint#127]
Hey friends,
I want to have Ember Build break on ESLint Errors.

Is this possible currently with this library or would I need to go and do this manually somewhere?

I found this but it is relevant to JSHint: https://discuss.emberjs.com/t/force-build-failure-on-any-jshint-error/7060/5

**Comment by Turbo87** [comment]
as you can see in the README there is a `throwOnError` option that you can use

**Comment by Alonski** [comment]
Oops how embarrassing I didn't notice :) Thanks!
