### ISSUE TITLE
Windows : Invalid regular expression

### ISSUE THREAD

**Issue by olivierchatry** [ember-cli/broccoli-lint-eslint#35]
Just updated to the latest ember cli, and got this error :
Invalid regular expression: /(\)?build(\)?$/: Unterminated group

It come from this line : 

```.js
var BUILD_DIR_REGEX = new RegExp('(' + path.sep + ')?build(' + path.sep + ')?$');
```

path.sep needs to be escaped as on windows it is '\' 

I fixed that like this :

```.js
var BUILD_DIR_REGEX = new RegExp('(\\' + path.sep + ')?build(\\' + path.sep + ')?$');
```

Should I create a pull request, or can someone directly fix that ?

Thanks !

**Comment by jonathanKingston** [comment]
Ideally path.sep should be escaped passing it through a function before it lands in here.
Probs was never tested in Windows, but it should always be escaped.
Will make a pull tonight if someone has not.

**Comment by olivierchatry** [comment]
Agreed. Is there is any such function within the addon ?

On Mon, Apr 18, 2016 at 1:32 PM, Jonathan Kingston <notifications@github.com

**Comment by jonathanKingston** [comment]
Personally I would add this: https://www.npmjs.com/package/escape-string-regexp

**Comment by olivierchatry** [comment]
Actually, this might be overkill, as seperator are always / or \ and
normally always needs to be escaped.

I'm not even sure how it can work know as linux style sep should be escaped
as well :/



On Mon, Apr 18, 2016 at 2:44 PM, Jonathan Kingston <notifications@github.com
