### ISSUE TITLE
Upgrade to eslint 3.0.x

### ISSUE THREAD

**Issue by BrianSipple** [ember-cli/broccoli-lint-eslint#40]
Now that ESLint 3.0 has been released, it would be a nice upgrade to get into broccoli-lint-eslint soon.

Potential Blockers:
  * [ESLint Node support](http://eslint.org/docs/user-guide/migrating-to-3.0.0#dropping-support-for-nodejs--4) should align with that of Ember CLI's

Useful links:
  * [Release notes](http://eslint.org/blog/2016/07/eslint-v3.0.0-released)
  * [Migration guide](http://eslint.org/docs/user-guide/migrating-to-3.0.0)

**Comment by Turbo87** [comment]
@BrianSipple keep in mind that Ember CLI committed to support Node 0.x until they fall out of LTS status and ESLint 3 dropped support for them

**Comment by BrianSipple** [comment]
@Turbo87 Ah, good point. I updated the issue to indicate that this might be one to wait on for a bit

**Comment by alexlafroscia** [comment]
Just to see what it would take, I tried it out locally.  Simply bumping the `eslint` version doesn't cause any of the tests to fail so it should be an easy upgrade.

Could you bump the version of this plugin to `3.0.0` as well, so that people have to manually opt into the upgrade?  Then they could decide for themselves if they want to upgrade and lose support for old versions of Node.

**Comment by BrianSipple** [comment]
@alexlafroscia Nice. I don't think we'll have any breaking changes requiring a major version bump that _aren't_ related to new developments in ESLint 3+, so I'd say we could totally do that. I'll get a PR ready.

**Comment by Turbo87** [comment]
Keep in mind that that means we have to maintain two versions of the addon in parallel for the time being. I'm okay with that but we should be aware that it's a little more work.

**Comment by BrianSipple** [comment]
Yep yep. I'm okay with it based on the fact that there doesn't seem to be much development left to be done for the 2.x line. I could be wrong, out course, but I think the benefits of getting out in front on a 3.x line would be worth it.

**Comment by alexlafroscia** [comment]
@BrianSipple if you want me to PR the branch that I bumped the version on, I can just do that.  It's [here](https://github.com/alexlafroscia/broccoli-lint-eslint/tree/eslint-3.0.0).

**Comment by BrianSipple** [comment]
@alexlafroscia That could work. 

A question I have, then, is what the best way to organize branches will be (cc @Turbo87).

I was thinking of having master reflect the 3.x line while also having a [separate branch tailored for 2.x support](https://github.com/ember-cli/broccoli-lint-eslint/tree/2.x). For users, we just need to document the difference in Node version compatibility.

**Comment by Turbo87** [comment]
@BrianSipple that's exactly what I would do too
