### ISSUE TITLE
Add support for setting `throwOnWarn` option

### ISSUE THREAD

**Issue by BrianSipple** [ember-cli/broccoli-lint-eslint#45]
After going through our what we're doing in our [`postProcess` hook](https://github.com/ember-cli/broccoli-lint-eslint/blob/master/lib/index.js#L182) -- checking for a `throwOnError` option and then reducing the severity count from a report result's `messages` [to a truthy number if we detect an error](https://github.com/ember-cli/broccoli-lint-eslint/blob/master/lib/index.js#L27) --  it seems like it would be pretty trivial to also check for `throwOnWarn` (or any arbitrary threshold, but perhaps that's another discussion 😄), reduce message severity into a raw sum, and then act accordingly from there. 

(Side note: We're actually iterating through messages before checking whether or not the user has even set `throwOnError`, but #44 addresses that as well)

**Comment by Turbo87** [comment]
@BrianSipple is this resolved now?

**Comment by BrianSipple** [comment]
@Turbo87 Ah, not yet. This would be a follow-on enhancement to #58. Now that #58 has been merged,  though, I have two PRs (including one addressing this) inbound shortly.
