### ISSUE TITLE
Cannot set throwOnError

### ISSUE THREAD

**Issue by baron1405** [ember-cli/broccoli-lint-eslint#7]
It appears that throwOnError is a property on internalOptions but there does not appear to be any way to set that. Am I missing something?

**Comment by jonathanKingston** [comment]
I suspect you are using the beta version which the API has changed:
https://github.com/jonathanKingston/broccoli-lint-eslint/tree/beta

**Comment by baron1405** [comment]
The version that is brought in by ember-cli-eslint 1.0.0-beta.13. Looks like 1.0.1.

**Comment by ericwooley** [comment]
So this doesn't appear to be working on 1.1.1, is there something different in the API I need to set?
