### ISSUE TITLE
Plans for migrating to ESLint 3.0?

### ISSUE THREAD

**Issue by mike-north** [ember-cli/broccoli-lint-eslint#76]
There are some new esnext patterns that require a lot of finesse in order to make ESLint 2 happy. For example, async arrow functions

```js
async function renderChapters(urls) {
  await Promise.all(urls.map(getJSON).map(async j => addToPage((await j).html)));
}
```

Are there plans to upgrade this addon? Should I make a new one?

**Comment by rwjblue** [comment]
I believe an eslint 3 version of both this and ember-CLI-eslint is already available. Due to ESLint dropping support for node 0.12 the default (aka latest tag on npm) is still using eslint 2.

**Comment by rwjblue** [comment]
It does look like the master branch needs to be updated with changes to the 2.x branch (and a new release) though.

**Comment by Turbo87** [comment]
correct, `master` is ESLint 3.x and `2.x` is ESLint 2.x. we'll support 2.x until the end of the year when Node 0.12 support is dropped.
